name: C/C++ CI

on: [push,pull_request]

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build Container
      uses: docker/build-push-action@v2
      with:
        context: .
        file: "${{ github.workspace }}/docker/Dockerfile"
        push: false
        tags: miplib:latest

    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: miplib:latest
        options: -v ${{ github.workspace }}:/var/www
        run: |
          cd /var/www
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j
