name: C/C++ CI

on: [push]

jobs:
  ubuntu-build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gnosispm/miplib-backends:1.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        run-test: true
