name: C/C++ CI

on: [push,pull_request]

jobs:
  ubuntu-build-and-test:
    runs:
      using: docker
      image: '${{ github.workspace }}/docker/Dockerfile'
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        build-type: Release
        run-test: true
