name: publish
on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Miplib image metadata
        id: meta_miplib
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          labels: |
            org.opencontainers.image.licenses=GPL-3.0-or-later

      - name: Miplib image build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.binary
          push: true
          tags: ${{ steps.meta_miplib.outputs.tags }}
          labels: ${{ steps.meta_miplib.outputs.labels }}
